spring:
  flyway:
    locations: classpath:db/migration
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG