/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import static com.google.common.base.MoreObjects.firstNonNull;

import com.google.common.collect.Lists;
import java.util.ArrayList;
import java.util.List;

public class HelloOtus {
    public static void main(String... args) {

        String s1 = "hello";
        String s2 = null;

        String s3 = firstNonNull(s2, s1);

        System.out.println(s3);

        List<Integer> example = new ArrayList<>();
        int min = 0;
        int max = 100;
        for (int i = min; i < max; i++) {
            example.add(i);
        }

        System.out.println(Lists.reverse(example));
    }
}
